V2 event/config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'events#index', as: 'home'
  get '/events/new', to: 'events#new', as: 'new_event'
  post '/events/new', to: 'events#create'
  get '/events/:id/show', to: 'events#show', as: 'event_show'
  get '/event/:id/suscribe', to: 'events#suscribe', as: 'suscribe'
  get '/event/:id/invite', to: 'events#invite', as: 'invite'
  post '/event/invite', to: 'events#share_invite', as: 'share_invite'

  
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/user/:id/show', to: 'sessions#show', as: 'current_user'


  get '/signup', to: 'user#new', as: 'signup'
  post '/signup', to: 'user#create', as: 'create_user'
  get '/users/:id/show', to: 'user#show', as: 'user_show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

V2 event/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

V2 event/app/models/event.rb
class Event < ApplicationRecord
  validates :description, presence: true
  validates :place, presence: true
  validates :date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees
  has_many :attendees, through: :event_attendees
end

V2 event/app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  validates :event_id, presence: true
  validates :attendee_id, presence: true
  belongs_to :event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

V2 event/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  has_many :attending_events, through: :event_attendees, source: :event
end

V2 event/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

V2 event/app/controllers/events_controller.rb
require 'date'

class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    if session[:user]
      @event = Event.find(params['id'])
      @creator = User.find(@event.creator_id)
      event_attending = EventAttendee.where(event_id: params[:id])
      @attendees = []
      event_attending.each do |a|
        @attendees.push(User.find(a.attendee_id))
      end
    else
      flash[:alert] = "Veuillez vous connecter svp!"
      redirect_to home_path
    end
  end

  def new
  end

  def create
    p params[:event][:description]
    event = Event.create(description: params[:event][:description], 
      place: params[:event][:place],
      date: Date.parse(params[:event][:date]))
      event.creator = User.find(session[:user]['id'])
      
      if event.valid?
        event.save
        flash[:success] = "Évènement créer avec succès!"
        redirect_to current_user_path(event.id)
    else
      flash[:error] = "Champ invalide!"
      redirect_to new_event_path
    end
  end

  def suscribe
    attending = EventAttendee.new
    event = Event.find(params[:id])
    attending.event = event
    attending.attendee = User.find(session[:user]['id'])
    if attending.valid?
      attending.save
      redirect_to event_show_path(event.id)
    else
      redirect_to home_path
    end
  end

  def invite
    u = User.all
    @potos = []
    @event = Event.find(params[:id])
    u.each do |x|
      @potos.push(x.name)
    end
  end
  def share_invite
    attending = EventAttendee.new
    attending.event = Event.find(params['event'])
    attending.attendee = User.find_by(name: params['potos'])
    if attending.valid?
      attending.save
      redirect_to event_show_path(params['event'])
    end
  end
end

V2 event/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def show
    if session[:user]
      @events = Event.where(creator_id: session[:user]['id'])
    else
      redirect_to new_event_path
    end
  end

  def create
    @user = User.find_by(name: params['session']['name'].downcase)
    p @user
    if @user != nil
      session[:user] = @user
      flash[:success] = "Bonjour #{@user.name}!"
      redirect_to home_path
    else
      flash[:error] = "#{params['session']['name']} n'est pas encore inscris!"
      redirect_to action: 'new'
    end
  end

  def destroy
    session.delete :user
    redirect_to home_path
  end
end

V2 event/app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
    user = User.create(name: params[:user][:name].downcase)
    p user
    if user.valid?
      user.save
      session[:user] = user
      flash[:success] = "Inscris avec succès!"
      redirect_to home_path
    else
      flash[:error] = "Nom invalide!"
      redirect_to signup_path
    end
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
      @event_attended = EventAttendee.where(attendee_id: params['id'])
      @events = []
      @event_attended.each do |e|
        @events.push(Event.find(e.event_id))
      end
    else
      redirect_to new_event_path
    end

    event_attending = EventAttendee.where(attendee_id: params[:id])
    @attendees = []
    event_attending.each do |a|
      @attendees.push(User.find(a.attendee_id))
    end
  end
end

V2 event/app/helpers/application_helper.rb
module ApplicationHelper
end

V2 event/app/helpers/events_helper.rb
module EventsHelper
end

V2 event/app/helpers/sessions_helper.rb
module SessionsHelper
end

V2 event/app/helpers/user_helper.rb
module UserHelper
end

V2 event/app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

V2 event/app/views/events/index.html.erb
<div class="center jumbotron">
  <h1>Liste de tous les évènements</h1>
</div>

<% if flash[:success] %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong><%= flash[:success] %></strong> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= flash[:alert] %></strong> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>


<div class=" mt-5 p-5 offset-lg-2 col-lg-8 shadow">
<div class="list-group">
<% @events.each do |e| %>
<a href="<%= event_show_path(e.id) %>" class="list-group-item list-group-item-action flex-column align-items-start">
  <div class="d-flex w-100 justify-content-between">
    <h5 class="mb-1"><b><%= e.place %></b></h5>
    <small><%= Date.parse(e.date.to_s).strftime('%a %d %b %Y') %></small>
  </div>
  <p class="mb-1">
    <%= e.description %>
  </p>
</a>
<% end %>
</div>
</div>

V2 event/app/views/events/invite.html.erb
<div class="center jumbotron">
  <h1>Inviter un potos !</h1>
</div>

<div class="bg-light mt-5 p-5 offset-lg-2 col-lg-8 shadow">

<%= form_tag share_invite_path, method: "post" do %>
    <%= hidden_field_tag 'event', @event.id %>
    <div class="form-group">
    <label for="potos">Liste des amis</label>
    <%= select_tag "potos", options_for_select(@potos), class: 'form-control' %>
    </div>
    <%= submit_tag "Envoyer", class: 'btn btn-primary' %>
<% end %>

</div>

V2 event/app/views/events/new.html.erb
<% provide(:title, "Create event") %>

<div class="center jumbotron">
  <h1>Créer un évènement</h1>
</div>

<div class="bg-light mt-5 p-5 offset-lg-2 col-lg-8 shadow">
<% if flash[:error] %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Echec!</strong> <%= flash[:error] %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<div class="row">
  <div class="col-md-8 offset-2 center">
    <%= form_for(:event, path: new_event_path) do |f| %>

    <div class="form-group">
      <%= f.label :Description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :Date %>
      <%= f.date_field :date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :Place %>
      <%= f.text_field :place, class: 'form-control' %>
    </div>

      <%= f.submit "Créer l'évènement", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

V2 event/app/views/events/show.html.erb
<div class="center jumbotron">
  <h1>creator: <%= @creator.name %></h1>
  <h3>
    Place: <em><%= @event.place %></em>
  </h3>
  <p><%= @event.description %></p>
  <small><%= Date.parse(@event.date.to_s).strftime('%a %d %b %Y') %></small><br>

  <%= link_to "Retour", home_path, class: "btn btn-lg btn-success" %>
  <%
    i = 0
    @attendees.each do |a|
      if a.id == session[:user]['id']
        i += 1
      end
    end
    if i > 0 
    %>
  <%= link_to "Rejoindre l'evenement", '#', class: "btn btn-lg btn-primary disabled" %>
  <%else%>
  <%= link_to "Rejoindre l'evenement", suscribe_path(@event.id), class: "btn btn-lg btn-primary" %>
  <%end%>
  <%= link_to "Inviter un potos", invite_path(@event.id), class: "btn btn-lg btn-warning" %>
</div>



<div class="shadow mt-5 p-5 bg-light">
  <table class="table table-striped table-dark">
    <thead>
      <tr class="bg-primary">
        <th scope="col">#</th>
        <th scope="col">Invités</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

      <%=%>
    
      <% @attendees.each do |a| %>
      <tr>
        <th scope="row"><%= a.id%></th>
        <td><%= a.name %></td>
        <td><%= link_to "Voir", user_show_path(a.id), class: 'btn btn-info' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

V2 event/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark shadow" style="background-color: #373634">
  <a class="navbar-brand" href="<%= home_path%>">Eventbrite Like⛵😇 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= home_path %>">Accueil</a>
      </li>
      <%if session[:user] %>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">Créer un évènement</a>
      </li>
      <%end%>
    </ul>
    <form class="form-inline">
      <%if session[:user] %>
      <a href="<%= logout_path(session[:user]['id'])%>" class="btn btn-outline-danger my-2 my-sm-0">Deconnexion</a>
      <%else%>
      <a href="<%= login_path%>" class="btn btn-outline-success my-2 my-sm-0">Se connecter ou s'inscrire?</a>
      <%end%>
    </form>
  </div>
</nav>

V2 event/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
  </body>
  <script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
</html>

V2 event/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

V2 event/app/views/user/new.html.erb
<% provide(:title, "Log in") %>

<div class="center jumbotron">
  <h1>S'inscrire</h1>
</div>

<div class="bg-light mt-5 p-5 offset-lg-2 col-lg-8 shadow">
<% if flash[:error] %>
<div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 center">
    <%= form_for(:user, url: create_user_path) do |f| %>

    <div class="form-group">
      <%= f.label :Pseudo %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

      <%= f.submit "S'inscrire", class: "btn btn-primary" %>
    <% end %>
    <br>

    <p><%= link_to "Se connecter!", login_path %></p>
  </div>
</div>

</div>

V2 event/app/views/user/show.html.erb
<div class="center jumbotron">
  <h1>la liste des évenements auquel <%= @user.name %> participe</h1>
</div>


<div class="shadow mt-5 p-5 bg-light">
  <table class="table table-striped table-dark">
    <thead>
      <tr class="bg-danger">
        <th scope="col">#</th>
        <th scope="col">Place</th>
        <th scope="col">Description</th>
        <th scope="col">Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

      <%=%>
    
      <% @events.each do |e| %>
      <tr>
        <th scope="row"><%= e.id%></th>
        <td><%= e.place %></td>
        <td><%= e.description %></td>
        <td><%= Date.parse(e.date.to_s).strftime('%a %d %b %Y') %></td>
        <td>
        <%= link_to "Voir", '', class: 'btn btn-info' %>
        <%
          i = 0
          @attendees.each do |a|
            if a.id == session[:user]['id']
              i += 1
            end
          end
          if i > 0 
          %>
        <%= link_to "Rejoindre l'evenement", '#', class: "btn btn-primary disabled" %>
        <%else%>
        <%= link_to "Rejoindre l'evenement", suscribe_path(e.id), class: "btn btn-primary" %>
        <%end%>
        
        <%= link_to "Inviter un potos", invite_path(e.id), class: "btn btn-warning" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>